### ISSUE TITLE
the report type about json

### ISSUE THREAD

**Issue by longjj** [SonarSource/sonarlint-cli#13]
Hello, recently my project need a light java static check tool for an online judge. I found your project pretty good while the report is html only and it is a little difficult to work with it.

I just wonder whether adding another output type as json is under your recent consideration, thanks a lot :)

**Comment by henryju** [comment]
We don't plan to extend SonarLint CLI to produce "technical" reports. If you need to integrate SonarLint with third party tool you should have a look at SonarLint Core library.
